# Generated by Django 4.2.20 on 2025-03-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_good_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
        ),
    ]
